### ISSUE TITLE
Rewrite the CLI in Rust

### ISSUE THREAD

**Issue by kelcecil** [alexjpaz/tilde-soundboard#12]
Can't do this Python biz. I need a Rust client. Please deliver. I can pay large amounts of blockchain Monopoly money.

**Comment by kelcecil** [comment]
Repo owner hasn't responded within 2 minutes. Project is dead.

**Comment by bcarpen6** [comment]
reopening cause of @kelcecil

**Comment by bcarpen6** [comment]
closing because of @kelcecil
